define(['jquery'],function(){$("#loginForm").submit(function(){var email=document.getElementById("login-email").value;var pawd=document.getElementById("login-password").value;if(email==''||pawd==''){$('.emailError').show();return false;}
var url=window.location.href;var urlStr="";if(url.indexOf(".html")>-1){urlStr=url.substr(0,url.lastIndexOf("."))+".mycnw.login.json";}else if(url.charAt(url.length-1)=="/"){urlStr=url.substr(0,url.lastIndexOf("/"))+".mycnw.login.json";}else{urlStr=url.substr(0,url.lastIndexOf("/"))+".mycnw.login.json";}
jQuery.ajax({type:'POST',url:urlStr,data:'InputEmail1='+email+'&InputPassword1='+pawd,success:function(json){var response=jQuery.parseJSON(json);var responseVal=response['val'];var responseCode=response['responseCode'];if(responseCode=="201"&&responseVal=='0'){if($('#remember').is(':checked')){var userID=email;setCookieData('userId',userID);setCookieData('remember',true);}else{setCookieData('remember',false);}
location.href="subscriptions.html";}else if(responseCode>="400"){setCookieData('remember',false);if(responseVal==-1){$('.emailError').show();return false;}else if(responseVal==-2){$('.emailError').show();return false;}else if(responseVal==-3){$('.resposeError').show();return false;}}},error:function(error){}});return false;});});function logOut()
{var url=window.location.href;var urlStr="";if(url.indexOf("int.newswire.ca")>-1||url.indexOf("uat.newswire.ca")>-1||url.indexOf("www.newswire.ca")>-1){if(url.indexOf("?")>-1){url=url.substr(0,url.lastIndexOf("?"));}
urlStr=url+"mycnw/logout.mycnw.logout.json";}else if(url.indexOf(".html")>-1){urlStr=url.substr(0,url.lastIndexOf("."))+".mycnw.logout.json";}else if(url.charAt(url.length-1)=="/"){urlStr=url.substr(0,url.lastIndexOf("/"))+".mycnw.logout.json";}else{urlStr=url.substr(0,url.lastIndexOf("/"))+".mycnw.logout.json";}
jQuery.ajax({type:'POST',url:urlStr,success:function(json){var response=jQuery.parseJSON(json);var responseCode=response['responseCode'];if(responseCode=="202"){if(url.match("uat.newswire.ca/fr")){location.href="https://uat.newswire.ca/fr";}else if(url.match("uat.newswire.ca")){location.href="https://uat.newswire.ca";}else if(url.match("www.newswire.ca/fr")){location.href="https://www.newswire.ca/fr";}else{location.href="https://www.newswire.ca";}}}});}
function setCookieData(c_name,ulang){var expiration_date=new Date();expiration_date.setFullYear(expiration_date.getFullYear()+1);var c_value=escape(ulang)+"; path=/; expires="+expiration_date.toGMTString();document.cookie=c_name+"="+c_value;}
function getCookieData(c_name){if(document.cookie.length>0){var c_start=document.cookie.indexOf(c_name+"=");if(c_start!=-1){c_start=c_start+c_name.length+1;c_end=document.cookie.indexOf(";",c_start);if(c_end==-1)c_end=document.cookie.length;return unescape(document.cookie.substring(c_start,c_end));}}
return "";}